### ISSUE TITLE
region_id or cloud_region_id

### ISSUE THREAD

**Issue by ankushdigitar** [zilliztech/terraform-provider-zillizcloud#40]
Hi team, 

I recently switched to official terraform provider, but I am facing errors like below: 

```
 Error: Missing required argument
│ 
│ The argument "cloud_region_id" is required, but was not set.
```

provider "zillizcloud" {
  api_key = var.zilliz_terraform_key 
}

But, cloud_region_id is not expected in this provider as per documentation. 

what am I missing?

**Comment by haorenfsa** [comment]
Hi @ankushdigitar  You may need following arguments as input to create a cluster
<img width="910" alt="image" src="https://github.com/user-attachments/assets/b216d578-706b-4f45-b6c6-7a73474c1dcd">

https://github.com/zilliztech/terraform-provider-zillizcloud/blob/master/docs/create-a-standard-cluster.md

**Comment by ankushdigitar** [comment]
Hi @haorenfsa , I am looking to create a serverless cluster which doesn't require the region_id
https://github.com/zilliztech/terraform-provider-zillizcloud/blob/master/docs/create-a-serverless-cluster.md

This is how I have setup the provider
```

terraform {
  required_providers {
    zillizcloud = {
      source = "zilliztech/zillizcloud"
      # version = "0.2.3"
    }
  }
}
```

`provider "zillizcloud" {
  api_key = var.zilliz_terraform_key # Send it via TF_VAR
}`

This comes back with an error on terraform apply 
` Error: Missing required argument
│ 
│ The argument "cloud_region_id" is required, but was not set.`

**Comment by ankushdigitar** [comment]
I tried all different combinations for provider and zillizcloud_cluster but, unfortunately I cannot get it to work. 

This is the error I get consistently. 

│ Error: Missing required argument
│ 
│ The argument "cloud_region_id" is required, but was not set.

**Comment by ankushdigitar** [comment]
I think the issue is rectified now. This is my finding: 

1. If you are switching from old provider, you need to terraform rm '<resource_name>' and then run this setup. Otherwise it will error out expecting the other provider that zilliz has. 

https://registry.terraform.io/providers/skyscrapr/zilliz/latest

**Comment by ankushdigitar** [comment]
Issue is closed

**Comment by haorenfsa** [comment]
Thank you @ankushdigitar! I think it would be very helpful if we put this in FAQ. cc @yellow-shine
